### REGISTER USER ###
POST http://localhost:3000/api/user    
Content-Type: application/json

{
  "email": "saanalytics.work@gmail.com",
  "password": "Saanalytics",
  "name": "SA Analytics AC1",
  "language": "en",
  "platform": "Android",
  "timezone": 0,
  "deviceId": "xxxxx"
}

###  LOGIN USER ###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "saanalytics.work@gmail.com",
    "password": "Saanalytics"
}

###  Edit User ###
PUT http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJmZDYzNjlmYjNlZTYwZWY3N2IzOGQiLCJpYXQiOjE3MDcwNzExMTMsImV4cCI6MTcwNzEwNzExM30.tyU-GjgLUhneiGe1MyYlFhDUxxDXfDSl4OCMwoLg2I8
Content-Type: application/json

{
  "name": "SA ANALYTICS AC1"
  // other information if present
}

### Check if the user is authenticated ### 
GET  http://localhost:3000/api/user/verify-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJmYzllMzg3MGIxOTZkMDQwY2ViNmUiLCJpYXQiOjE3MDcwNjg3OTksImV4cCI6MTcwNzEwNDc5OX0.RQT_gl-5rfaU6yiOLcCdM8UZT3qjVs9gmgblFZyqcP4

### Refresh the acess token
POST http://localhost:3000/api/user/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE5NTRlYjk5YWRlZTEzZmY2ZmE3YjIiLCJpYXQiOjE3MDU2NzM5NjYsImV4cCI6MTcwNjI3ODc2Nn0.RVAmiyQPaBUmZfREu85L2esq0W8m0FTZYvPlBDZA9Yo"
}

### Change Password ###
POST http://localhost:3000/api/user/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWE5NTRlYjk5YWRlZTEzZmY2ZmE3YjIiLCJpYXQiOjE3MDU2NzM2MjksImV4cCI6MTcwNTcwOTYyOX0.YKkEoHGy0sBqlw9UBUVZcRtPchPmv-3n1pfjCfhPWGI
Content-Type: application/json

{
  "oldPassword": "amanshukla123@",
  "newPassword": "amanshukla123@"
}

### delete a user ### 
DELETE  http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWJmYzllMzg3MGIxOTZkMDQwY2ViNmUiLCJpYXQiOjE3MDcwNjg3OTksImV4cCI6MTcwNzEwNDc5OX0.RQT_gl-5rfaU6yiOLcCdM8UZT3qjVs9gmgblFZyqcP4



